### ISSUE TITLE
Configuration for Vulkan

### ISSUE THREAD

**Issue by Mirkopoj** [svenstaro/glsl-language-server#22]
Fist of all, congratulation on this great tool.

I'm writing some vulkan shaders and get some lsp errors saying:
```
'<some-feature>' : only allowed when using GLSL for Vulkan
```
Is there a way to tell the lsp that I'm indeed using GLSL for Vulkan, similar to compile_flags.txt for clangd based lsp?

Thank you in advance.

**Comment by Mirkopoj** [comment]
https://github.com/svenstaro/glsl-language-server/compare/master...pudnax:glsl-language-server:master

Found a fork that solves it.

**Comment by svenstaro** [comment]
This doesn't really fix it here though, does it? We shouldn't settle for forks. The work should be upstreamed so that others won't be confused.
