### ISSUE TITLE
Unable to package in Fedora

### ISSUE THREAD

**Issue by mkoncek** [svenstaro/glsl-language-server#33]
I wanted to package this project as a Fedora package.
* First issue is that your project source bundles all its dependencies, that is unacceptable but can be fixed on our side by replacing dependencies with the system ones. It would be nice if your Cmakefile use standard ways of searching for system dependencies and linking with them.

* Another worse problem is that your project depends on mongoose 6.9 and on functions which are no longer present in the latest version 7.10. Would it be possible for you to update your dependencies?

**Comment by svenstaro** [comment]
I'd still like to be a better upstream here but frankly I think I'll sooner be rewriting this in Rust than spending time getting C++ dependencies right.

**Comment by mkoncek** [comment]
I recently rewrote a good chunk of my hobby code to Rust, it is doable after some time investment...

**Comment by svenstaro** [comment]
I'm really quite comfortable writing Rust so that's not much of an issue.

**Comment by mkoncek** [comment]
There is a different project but that is not even usable in Kate text editor: https://github.com/KubaP/glsl-lsp

**Comment by svenstaro** [comment]
Oh, I had no idea. That's great!
